spring:
  profiles:
    active: local

  #  datasource:
  #    url: jdbc:h2:mem:test
  #    username: sa
  #    password:
  #    driver-class-name: org.h2.Driver
  #  h2:
  #    console:
  #      enabled: true
  #      path: /h2-console
  datasource:
    url: jdbc:mysql://localhost:3306/todo?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Password!

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        format_sql: true
        show_sql: true