spring:
  profiles:
    active: dev

---

spring:
  datasource:
    url: jdbc:h2:tcp://localhost:8080/mem:testdb;MVCC=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: H2
    show-sql: false
    hibernate:
      ddl-auto: create-drop

  config:
    activate:
      on-profile: dev


---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board_tdd?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Password!


  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    //show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  devtools:
    livereload:
      enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

  config:
    activate:
      on-profile: prod

  flyway:
    enabled: true
    baseline-on-migrate: true