spring:
  datasource:
    url: jdbc:mysql://${DB_SERVER}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Password!

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    show-sql: true
    database: mysql


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
